### ISSUE TITLE
训练完，如何测试自己手写的数字呢

### ISSUE THREAD

**Issue by sunfeng90** [LightningLeader/Matlab-builds-AlexNet-to-realize-handwritten-digit-recognition#1]
很优秀的工作。我训练完这个，然后测试自己手写的数字图片呢？

**Comment by sunfeng90** [comment]
如何识别自己的手写数字呢

**Comment by sunfeng90** [comment]
用你的数据集，识别率只有9%。

**Comment by sunfeng90** [comment]
你是如何将mnist原始数据集，转换成bpm的？

**Comment by LightningLeader** [comment]
> 用你的数据集，识别率只有9%。

我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。

**Comment by LightningLeader** [comment]
> 你是如何将mnist原始数据集，转换成bpm的？

[关于官方mnist手写数据集转换为jpg格式](https://blog.csdn.net/lhd_96/article/details/135173807)
可以参考这类博客将原始数据集转换成其他图片格式。

**Comment by LightningLeader** [comment]
> 很优秀的工作。我训练完这个，然后测试自己手写的数字图片呢？

你可能需要将训练好的模型保存，然后再另外加载这个保存好的模型。将测试图像处理成与训练数据相同的格式，差不多就可以传入进行测试了。

**Comment by sunfeng90** [comment]
好的，谢谢

**Comment by sunfeng90** [comment]
> > 你是如何将mnist原始数据集，转换成bpm的？
> 
> [关于官方mnist手写数据集转换为jpg格式](https://blog.csdn.net/lhd_96/article/details/135173807) 可以参考这类博客将原始数据集转换成其他图片格式。

你是按照这个生成0-9的数据集和测试集的吗？

**Comment by sunfeng90** [comment]
> > 用你的数据集，识别率只有9%。
> 
> 我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。

你Readme里面生成图片的结果，是通过很多训练的数据，来获得的吗？

**Comment by LightningLeader** [comment]
> > > 你是如何将mnist原始数据集，转换成bpm的？
> > 
> > 
> > [关于官方mnist手写数据集转换为jpg格式](https://blog.csdn.net/lhd_96/article/details/135173807) 可以参考这类博客将原始数据集转换成其他图片格式。
> 
> 你是按照这个生成0-9的数据集和测试集的吗？
是的，训练数据集是每种数字单独一个文件夹。测试集的话应该可以随意传入。

**Comment by LightningLeader** [comment]
> > > 你是如何将mnist原始数据集，转换成bpm的？
> > 
> > 
> > [关于官方mnist手写数据集转换为jpg格式](https://blog.csdn.net/lhd_96/article/details/135173807) 可以参考这类博客将原始数据集转换成其他图片格式。
> 
> 你是按照这个生成0-9的数据集和测试集的吗？

是的，训练数据集是每种数字单独的文件夹。测试集应该可以传入单张吧。

**Comment by LightningLeader** [comment]
> > > 用你的数据集，识别率只有9%。
> > 
> > 
> > 我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。
> 
> 你Readme里面生成图片的结果，是通过很多训练的数据，来获得的吗？

只训练了我自己的数据集，也没有太多吧，训练集每个数字才30张，验证集20张。

**Comment by sunfeng90** [comment]
> > > > 用你的数据集，识别率只有9%。
> > > 
> > > 
> > > 我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。
> > 
> > 
> > 你Readme里面生成图片的结果，是通过很多训练的数据，来获得的吗？
> 
> 只训练了我自己的数据集，也没有太多吧，训练集每个数字才30张，验证集20张。

确实，但是准确率就2.9%；

**Comment by LightningLeader** [comment]
> > > > > 用你的数据集，识别率只有9%。
> > > > 
> > > > 
> > > > 我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。
> > > 
> > > 
> > > 你Readme里面生成图片的结果，是通过很多训练的数据，来获得的吗？
> > 
> > 
> > 只训练了我自己的数据集，也没有太多吧，训练集每个数字才30张，验证集20张。
> 
> 确实，但是准确率就2.9%；

你测试的是什么数据？是自己手写/准备的数据吗？训练参数有没有改过？

**Comment by sunfeng90** [comment]
> > > > > > 用你的数据集，识别率只有9%。
> > > > > 
> > > > > 
> > > > > 我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。
> > > > 
> > > > 
> > > > 你Readme里面生成图片的结果，是通过很多训练的数据，来获得的吗？
> > > 
> > > 
> > > 只训练了我自己的数据集，也没有太多吧，训练集每个数字才30张，验证集20张。
> > 
> > 
> > 确实，但是准确率就2.9%；
> 
> 你测试的是什么数据？是自己手写/准备的数据吗？训练参数有没有改过？

就是手动写几个数字，然后识别出来。可能是单个数字，可能是连续的数字。例如1，或者54321

**Comment by sunfeng90** [comment]
如果是连续的54321，就切割开来，先识别5，再识别4。。。你有时间一起搞吗？

**Comment by sunfeng90** [comment]
有红包作为报酬，怎么样

**Comment by sunfeng90** [comment]
> > > > > > 用你的数据集，识别率只有9%。
> > > > > 
> > > > > 
> > > > > 我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。
> > > > 
> > > > 
> > > > 你Readme里面生成图片的结果，是通过很多训练的数据，来获得的吗？
> > > 
> > > 
> > > 只训练了我自己的数据集，也没有太多吧，训练集每个数字才30张，验证集20张。
> > 
> > 
> > 确实，但是准确率就2.9%；
> 
> 你测试的是什么数据？是自己手写/准备的数据吗？训练参数有没有改过？

没有改过训练的数据，直接把你的数据拿过来训练和测试的。

**Comment by LightningLeader** [comment]
> > > > > > > 用你的数据集，识别率只有9%。
> > > > > > 
> > > > > > 
> > > > > > 我这个代码只是简单演示一下训练过程，识别率差很正常。如果想要获得更好的识别率，可以考虑增加训练数据的数量和使用效果更好的网络模型训练。
> > > > > 
> > > > > 
> > > > > 你Readme里面生成图片的结果，是通过很多训练的数据，来获得的吗？
> > > > 
> > > > 
> > > > 只训练了我自己的数据集，也没有太多吧，训练集每个数字才30张，验证集20张。
> > > 
> > > 
> > > 确实，但是准确率就2.9%；
> > 
> > 
> > 你测试的是什么数据？是自己手写/准备的数据吗？训练参数有没有改过？
> 
> 没有改过训练的数据，直接把你的数据拿过来训练和测试的。

那就不太清楚了。不好意思，我现在已经不怎么搞这东西了。如果还有什么问题的话，可以再讨论讨论。你说的这个东西，我建议还是用python完成，结合opencv和深度学习来做应该可以取得较好的效果吧。
